-- SQLite Data Backup
-- Generated: Fri Nov 07 11:49:10 WIB 2025

INSERT OR IGNORE INTO data_stiker VALUES ('1', '1', 'Rengginang Agung - 25001', '4', 'Bulat', '4', '1762489718016', '1762489718017', '1');

INSERT OR IGNORE INTO data_umkm VALUES ('1', 'Dusun III, Pahang, Talawi, Kab. Batu Bara, Sumatera Utara', '-', '85212138956', 'Zulfan Manurung', 'Rengginang Agung');
INSERT OR IGNORE INTO data_umkm VALUES ('2', 'Dusun III, Pahang, Talawi Kab. Batu Bara Sumatera Utara', '-', '82273769100', 'Nurhayati', 'UD. Maju Jaya');
INSERT OR IGNORE INTO data_umkm VALUES ('3', 'Dusun IV, Tanah Rendah, Air Putih Kab. Batu Bara Sumatera Utara', '-', '85270560183', 'Junaidi', 'Cheyla Food');
INSERT OR IGNORE INTO data_umkm VALUES ('4', 'Jl. Lintas Medan Kisaran Km 100, Tanah Rendah, Air Putih Kab. Batu Bara Sumatera Utara', '-', '82369401638', 'Indah', 'Kerajinan Kain Flanel');
INSERT OR IGNORE INTO data_umkm VALUES ('5', 'Jl. lintas Medan KisaranSamping Bri Depan Showroom Yamaha Horas No 299, Indrasakti, Air Putih Kab. Batu Bara Sumatera Utara', '-', '85203008824', 'Sri Intan', 'GULENIKA');
INSERT OR IGNORE INTO data_umkm VALUES ('6', 'DUSUN II KEBUN KAPAS DESA PERKOTAAN KECAMATAN AIR PUTIH KABUPATEN BATUBARA Kab. Batu Bara Sumatera Utara', '-', '0', 'BANJARAN JAYA MANDIRI', 'SITI NUR HADIJAH');
INSERT OR IGNORE INTO data_umkm VALUES ('7', 'jl. medan kisaran gg. Kuini, Aras, Air Putih Kab. Batu Bara Sumatera Utara', '-', '81285091884', 'Nur Dewi', 'Kue Cincin');
INSERT OR IGNORE INTO data_umkm VALUES ('8', 'Indrapura kota Kab. Batu Bara Sumatera Utara', '-', '82272768400', 'andriano', 'Burger 88');
INSERT OR IGNORE INTO data_umkm VALUES ('9', 'Dusun I, Perupuk, Limapuluh Kab. Batu Bara Sumatera Utara', '-', '81210363543', 'Sederhana', 'Sederhanas Craft');
INSERT OR IGNORE INTO data_umkm VALUES ('10', 'Jalan Lintas Sipare Pare, Sipare-Pare, Air Putih Kab. Batu Bara Sumatera Utara', '-', '85261004133', 'Gema Wijaya', 'Leony Salon');
INSERT OR IGNORE INTO data_umkm VALUES ('11', 'Dusun II, Padang Genting, Talawi Kab. Batu Bara Sumatera Utara', '-', '85371572345', 'Dahniar', 'Songket Batu Bara');
INSERT OR IGNORE INTO data_umkm VALUES ('12', 'Dusun III, Padang Genting, Talawi Kab. Batu Bara Sumatera Utara', '-', '81376295968', 'Elfi Zahara', 'Songket Zahara');
INSERT OR IGNORE INTO data_umkm VALUES ('13', 'Dusun III, Padang Genting, Talawi Kab. Batu Bara Sumatera Utara', '-', '82170919238', 'Jamilah', 'Tenun Batu Bara');
INSERT OR IGNORE INTO data_umkm VALUES ('14', 'Dusun IV, Padang Genting, Talawi Kab. Batu Bara Sumatera Utara', '-', '85358655281', 'Aisyah', 'Aisyah Songket');
INSERT OR IGNORE INTO data_umkm VALUES ('15', 'Dusun III, Padang Genting, Talawi Kab. Batu Bara Sumatera Utara', '-', '82360778631', 'Eva Dewi', 'Eva Songket');
INSERT OR IGNORE INTO data_umkm VALUES ('16', 'Perumahan Griya Indrapura Asri Blok F No.13 Kab. Batu Bara Sumatera Utara', '-', '82370066823', 'Oktavilia', 'Sepatu Rajut');
INSERT OR IGNORE INTO data_umkm VALUES ('17', 'Dusun II, Padang Genting, Talawi Kab. Batu Bara Sumatera Utara', '-', '85275088195', 'Khodijah', 'Songket Batu Bara');
INSERT OR IGNORE INTO data_umkm VALUES ('18', 'Dusun III, Padang Genting, Talawi Kab. Batu Bara Sumatera Utara', '-', '85362049678', 'Rodiah', 'Tenun Songket');
INSERT OR IGNORE INTO data_umkm VALUES ('19', 'Dusun III, Padang Genting, Talawi Kab. Batu Bara Sumatera Utara', '-', '85362049678', 'Zahratul Khodila', 'Tenun Songket');
INSERT OR IGNORE INTO data_umkm VALUES ('20', 'Dusun III, Padang Genting, Talawi Kab. Batu Bara Sumatera Utara', '-', '81370050269', 'Maisayarah', 'Songket Batu Bara');
INSERT OR IGNORE INTO data_umkm VALUES ('21', 'Dusun I , Padang Genting, Talawi Kab. Batu Bara Sumatera Utara', '-', '82166026136', 'Suheri Agustin', 'ATK');
INSERT OR IGNORE INTO data_umkm VALUES ('22', 'Dusun III, Padang Genting, Talawi Kab. Batu Bara Sumatera Utara', '-', '81275710631', 'Ramli Batu Bara', 'Songket Batu Bara');
INSERT OR IGNORE INTO data_umkm VALUES ('23', 'Dusun III, Padang Genting, Talawi Kab. Batu Bara Sumatera Utara', '-', '81366617427', 'Nuraisyah', 'Songket Batu Bara');
INSERT OR IGNORE INTO data_umkm VALUES ('24', 'Dusun III, Padang Genting, Talawi Kab. Batu Bara Sumatera Utara', '-', '82361770356', 'Tuti Astri', 'RM COLOMBIA');
INSERT OR IGNORE INTO data_umkm VALUES ('25', 'DUSUN 1, Guntung, Limapuluh Kab. Batu Bara Sumatera Utara', '-', '82166123551', 'MHD ILHAM SYAPUTRA', 'ILHAM PARCEL ');
INSERT OR IGNORE INTO data_umkm VALUES ('26', 'Tanjung Kubah Kab. Batu Bara Sumatera Utara', '-', '82304473638', 'Rawati Sihaloho', 'Renda RA');
INSERT OR IGNORE INTO data_umkm VALUES ('27', 'Dusun VII, Perk. Lima Puluh, Kec. Lima Puluh Kab. Batu Bara Sumatera Utara', '-', '82366837428', 'Sukarman', 'Kakek Nenek');
INSERT OR IGNORE INTO data_umkm VALUES ('28', 'Dusun I, Pulau Sejuk, Limapuluh Kab. Batu Bara Sumatera Utara', '-', '81361074167', 'Mazlan', 'Pande Besi Apel');
INSERT OR IGNORE INTO data_umkm VALUES ('29', 'Dusun 2 desa padang genting. Kab. Batu Bara Sumatera Utara', '-', '85763914046', 'Siti aminah', 'Syahira Songket');
INSERT OR IGNORE INTO data_umkm VALUES ('30', 'DUSUN III, Padang Genting, Talawi Kab. Batu Bara Sumatera Utara', '-', '85372436227', 'Yusnita', 'Ita Songket');
INSERT OR IGNORE INTO data_umkm VALUES ('31', 'Dusun III, Sentang, Tanjung Tiram Kab. Batu Bara Sumatera Utara', '-', '85359782667', 'Legirah', 'Kreatif Lidi ');
INSERT OR IGNORE INTO data_umkm VALUES ('32', 'Dusun I (tamsis), Simpang Kopi, Sei Suka Kab. Batu Bara Sumatera Utara', '-', '81397903476', 'Nurdiana', 'Dimas Jaya');
INSERT OR IGNORE INTO data_umkm VALUES ('33', 'DUSUN III DESA SUKARAJA Kab. Batu Bara Sumatera Utara', '-', '81361425294', 'ZULKIFLI', 'ESA PERABOT');
INSERT OR IGNORE INTO data_umkm VALUES ('34', 'Indrasakti, lingkungan IV indrapura, kecamatan Air Putih Kab. Batu Bara Kab. Batu Bara Sumatera Utara', '-', '82383416069', 'Agus Putra. sH', 'Family Foto');
INSERT OR IGNORE INTO data_umkm VALUES ('35', 'Dusun IX Desa Bandar Sono Kec. Tanjung Tiram Kab. Batu Bara Kab. Batu Bara Sumatera Utara', '-', '85262136020', 'Muhammad rozi', 'Gas Elfiji');
INSERT OR IGNORE INTO data_umkm VALUES ('36', 'Dusun II, Pakam, Medang Deras Kab. Batu Bara Sumatera Utara', '-', '85261048820', 'Rizal', 'Koperasi Mandiri Sejahtera Berjaya');
INSERT OR IGNORE INTO data_umkm VALUES ('37', 'Dusun I Seroja, Suka Ramai, Sei balai Kab. Batu Bara Sumatera Utara', '-', '85262797134', 'Sumarni', 'Aneka Keripik');
INSERT OR IGNORE INTO data_umkm VALUES ('38', 'Jl. Imam Bonjol, Labuhan Ruku, Kabupaten Batu Bara Kota Tanjung Balai Sumatera Utara', '-', '82167567562', 'Fitri', 'Succulent Home');
INSERT OR IGNORE INTO data_umkm VALUES ('39', 'Dusun Tasak Lama, Desa Lalang, Kecamatan Medang Deras, Kabupaten Batu Bara Kab. Batu Bara Sumatera Utara', '-', '82162064220', 'Khairul Syahbani', 'Bany Ceper');
INSERT OR IGNORE INTO data_umkm VALUES ('40', 'Dusun 2 desa padang genting  Kab. Batu Bara Sumatera Utara', '-', '82362507437', 'Lisma susanti', 'Tenun songket isma');
INSERT OR IGNORE INTO data_umkm VALUES ('41', 'Dusun 2, Desa Padang genting Kab. Batu Bara Sumatera Utara', '-', '82276455982', 'ANDRIATI', 'ANDRIATI');
INSERT OR IGNORE INTO data_umkm VALUES ('42', 'Dusun2 Desa padang genting Kab. Batu Bara Sumatera Utara', '-', '85358077042', 'Nurhayati', 'Tenun nurhayati');
INSERT OR IGNORE INTO data_umkm VALUES ('43', 'Jalan manunggal, Dusun 2,  Desa Padang genting" Kab. Batu Bara Sumatera Utara', '-', '82363669690', 'RAHAYU NISMI', 'RAHAYU NISMI');
INSERT OR IGNORE INTO data_umkm VALUES ('44', 'Dusun 2 Desa padang genting Kab. Batu Bara Sumatera Utara', '-', '85358077042', 'Filu wati', 'Tenun songket filu');
INSERT OR IGNORE INTO data_umkm VALUES ('45', 'Dusun 2 Desa padang genting Kab. Batu Bara Sumatera Utara', '-', '85355559637', 'Nur indah sari', 'Tenun songket sari');
INSERT OR IGNORE INTO data_umkm VALUES ('46', 'Dusun 2 Desa padang genting Kab. Batu Bara Sumatera Utara', '-', '85358077042', 'Filu wati', 'Tenun songket filu');
INSERT OR IGNORE INTO data_umkm VALUES ('47', 'Dusun 2 desa padang genting Kab. Batu Bara Sumatera Utara', '-', '85261809164', 'Lili rostati', 'Lili Rostati');
INSERT OR IGNORE INTO data_umkm VALUES ('48', 'Dusun 2, Jalan manunggal, Desa padang genting, Kecamatan talawi, Kabupaten batu bara Kab. Batu Bara Sumatera Utara', '-', '81375793538', 'AZIMAH', 'AZIMAH');
INSERT OR IGNORE INTO data_umkm VALUES ('49', 'Dusun 2, jalan manunggal sejanggat, desa padang genting, Kecamatan talawi kabupaten batu bara" Kab. Batu Bara Sumatera Utara', '-', '81263102142', 'rina wahyuni', 'Rina wahyuni');
INSERT OR IGNORE INTO data_umkm VALUES ('50', 'Jalan manunggal dusun 2, Desa padang genting Kab. Batu Bara Sumatera Utara', '-', '81362323936', 'Zumiali', 'Zumiali Songket');
INSERT OR IGNORE INTO data_umkm VALUES ('51', 'Dusun 2, jalan manunggal sejanggat, desa padang genting, Kecamatan talawi kabupaten batu bara" Kab. Batu Bara Sumatera Utara', '-', '82370701713', 'Rohani', 'Rohani');
INSERT OR IGNORE INTO data_umkm VALUES ('52', 'Jalan manunggal dusun 2, Desa padang genting Kab. Batu Bara Sumatera Utara', '-', '81370050', 'Tanti', 'Tenun Tanti');
INSERT OR IGNORE INTO data_umkm VALUES ('53', 'Dusun 2Jalan manunggalDesa padang gentingKecamatan talawi kabupaten batu bara Kab. Batu Bara Sumatera Utara', '-', '82162680185', 'Jumiati', 'Jumiati');
INSERT OR IGNORE INTO data_umkm VALUES ('54', 'Dusun2 manunggal sejangat Kab. Batu Bara Sumatera Utara', '-', '85358077042', 'Fatimah', 'Fatima songket');
INSERT OR IGNORE INTO data_umkm VALUES ('55', 'dusun 7 desa kampung kelapa Kab. Batu Bara Sumatera Utara', '-', '81265059115', 'januari simbolon', 'dagang saprodi');
INSERT OR IGNORE INTO data_umkm VALUES ('56', 'Jl. Ir Sutami, Tanah Rendah, Air Putih Kab. Batu Bara Sumatera Utara', '-', '8126470445', 'Sabaruddin', 'Tiga Dimensi Paving Block ');
INSERT OR IGNORE INTO data_umkm VALUES ('57', 'Jl. T. Hasan Serawak Dsn VII Desa Ujung Kubu Kab. Batu Bara Sumatera Utara', '-', '85361101731', 'Muhammad Nurdin', 'Rumah Kreatif GM Batu Bara');
INSERT OR IGNORE INTO data_umkm VALUES ('58', 'Kayu ara dsn 3 desa pahang, Kecamatan talawi kabupatenbatu bara" Kab. Batu Bara Sumatera Utara', '-', '82360492743', 'Ridwan', 'Usaha jahit');
INSERT OR IGNORE INTO data_umkm VALUES ('59', 'Jalan Sutan Sahrir Dusun V Bunga Cina Desa Barung-Barung Kab. Batu Bara Sumatera Utara', '-', '85261999911', 'NURHAYATI', 'Tenun Annur');
INSERT OR IGNORE INTO data_umkm VALUES ('60', 'Dusun Sei Gelanggang, Desa Padang Genting, Kec. Talawi, Kab. Batubara Kab. Batu Bara Sumatera Utara', '-', '81262256788', 'Habibah', 'Istana Songket Batubara');
INSERT OR IGNORE INTO data_umkm VALUES ('61', 'Indrapura kota,kabupaten batu bara gg kadhi Kab. Batu Bara Sumatera Utara', '-', '82163146502', 'Nur chairunnisya', 'Risolespakdaus');
INSERT OR IGNORE INTO data_umkm VALUES ('62', 'Jalan syeh H Muhammad Zein Jawi Guntung tengahDesa guntungKecamatan lima puluh pesisirKabupaten batubara Kab. Batu Bara Sumatera Utara', '-', '81372034100', 'Haris candra', 'Dangai Limonam');
INSERT OR IGNORE INTO data_umkm VALUES ('63', 'jln. Kiara Payung Blok T14 no 03 Tanjung gading Perum PT Inalum Kab. Batu Bara Sumatera Utara"', '-', '8126317993', 'Indah Dwifayati Nasution', 'IndSQuee');
INSERT OR IGNORE INTO data_umkm VALUES ('64', 'Dusun 1, Desa Sumber Padi, Kecamatan Lima Puluh Kab. Batu Bara Sumatera Utara', '-', '81260402712', 'Meimuna', 'Nabilka');
INSERT OR IGNORE INTO data_umkm VALUES ('65', 'Jl. Lintas Petatal. Desa Mekar Baru, Dusun I. Kecamatan Tanah Datar  ', '-', '85261107759', 'Leily Daryani', 'Herman Roti');
INSERT OR IGNORE INTO data_umkm VALUES ('66', 'Dusun VI Desa Kuala Tanjung Kecamatan Sei Suka Kabupaten Batu Bara Kab. Batu Bara Sumatera Utara', '-', '82365481230', 'Rika wahyuni hasibuan', 'ES JEDOT ILDARIWA mitra PT PELINDO I ');
INSERT OR IGNORE INTO data_umkm VALUES ('67', 'Jl. Dusun VI Pematang Kapas, Desa Kuala Tanjung Kec. Sei Suka Kab. Batubara  ', '-', '82162676918', 'Yenni Anggreani', 'Y&D Collection Mitra PT. Pelindo I');
INSERT OR IGNORE INTO data_umkm VALUES ('68', 'Desa Padang Genting   ', '-', '85361360630', 'MAKMUR ', 'TENUN SONGKET BATU BARA AISYAH MAKMUR mitra PELINDO I ');
INSERT OR IGNORE INTO data_umkm VALUES ('69', 'Desa Perupuk Kecamatan Lima Puluh Kota  ', '-', '82290201197', 'Citia Dewi', 'Dewix Craft');
INSERT OR IGNORE INTO data_umkm VALUES ('70', 'Jl. Acces Road Inalum, Kuala Tanjung, Pajak Sore Kab. Batu Bara Sumatera Utara', '-', '82166123551', 'Muhammad Ilham', 'Toko Mandiri');
INSERT OR IGNORE INTO data_umkm VALUES ('71', 'Jl. Besar Simpang Tiga Kab. Batu Bara Sumatera Utara', '-', '81268721850', 'Lims Datino', 'Kedai Datin');
INSERT OR IGNORE INTO data_umkm VALUES ('72', 'Jl. Imam Bonjol, Labuhan Ruku, Talawi Kab. Batu Bara Sumatera Utara', '-', '82277986744', 'Dewi Cipta', 'Griya Cipta');
INSERT OR IGNORE INTO data_umkm VALUES ('73', 'Jl. Lintas Medan Kisaran, Indrapura Kota Kab. Batu Bara Sumatera Utara', '-', '81376204948', 'Khairunnisa', 'Risoles Pak Daus');
INSERT OR IGNORE INTO data_umkm VALUES ('74', 'Dusun II Tanjung Kubah Kec. Air Putih Kab Batu Bara Kab. Batu Bara Sumatera Utara', '-', '82370724948', 'Desminar Debora Rangkuti', 'The Bora');
INSERT OR IGNORE INTO data_umkm VALUES ('75', 'Dusun VI Desa Air Hitam Kab.Batu Bara Sumatera Utara Kab. Batu Bara Sumatera Utara', '-', '82367563619', 'SANTI KARTINI SITINJAK', 'GOLDEN KIDS');
INSERT OR IGNORE INTO data_umkm VALUES ('76', 'Dusun Kulon Panduk Desa Pulau sejuk Kec.Lima Puluh Kab Batubara Kab. Batu Bara Sumatera Utara', '-', '82274147113', 'Nurdillah', 'Design_Project');
INSERT OR IGNORE INTO data_umkm VALUES ('77', 'Dusun Kompil, Desa Pulau Sejuk Kab. Batu Bara Sumatera Utara', '-', '82294390074', 'Yusmalina', 'Kedai Yoes');
INSERT OR IGNORE INTO data_umkm VALUES ('78', 'Dusun I Desa Air Hitam  Kab. Batu Bara Sumatera Utara', '-', '81269971311', 'Maisyarah', 'Kedai Makan Ainun');
INSERT OR IGNORE INTO data_umkm VALUES ('79', 'Jalan Desa Cahaya Pardomuan Dusun VI , Limapuluh , Kab Batu Bara  ', '-', '82364517877', 'Bintang Kasih', 'Bintang Karunia Rumahorbo');
INSERT OR IGNORE INTO data_umkm VALUES ('80', 'Lingkungan i, Kelurahan Bunut, Kisaran Barat Kab. Asahan Sumatera Utara', '-', '82166963339', 'Sutomo', 'Baizuri Boenoet Shoes');
INSERT OR IGNORE INTO data_umkm VALUES ('81', 'Dusun V, Sei Balai Kab. Batu Bara Sumatera Utara', '-', '82367439909', 'Ika Fitriana Tanjung', 'Rumah Loundry');
INSERT OR IGNORE INTO data_umkm VALUES ('82', 'Jl. Perintis Kemerdekaan, No. 20 Kab. Batu Bara Sumatera Utara', '-', '81212609578', 'Suryadi', 'Ayam Potong Suryadi');
INSERT OR IGNORE INTO data_umkm VALUES ('83', 'JL. Perintis Kemerdekaan Kab. Batu Bara Sumatera Utara', '-', '81262295777', 'Zakaria', 'Anahal Berkah');
INSERT OR IGNORE INTO data_umkm VALUES ('84', 'JL. Tuanku Imam Bonjol Kab. Batu Bara Sumatera Utara', '-', '82273258695', 'Nur Hasanah', 'Hasanah Shop');
INSERT OR IGNORE INTO data_umkm VALUES ('85', 'Jl. Rahmatsyah Desa Lalang Kab. Batu Bara Sumatera Utara', '-', '85277443106', 'Mariana', 'Salon Muslimah Mom Imar');
INSERT OR IGNORE INTO data_umkm VALUES ('86', 'Dusun VI Desa Air Hitam Kecamatan Datuk Lima Puluh Kabupaten Batu Bara Kab. Batu Bara Sumatera Utara', '-', '81212451335', 'Mita Wati Gultom', 'Mita Clothes Shop');

INSERT OR IGNORE INTO orderan_stiker VALUES ('1', 'RBBB-25110001', '1762489727126', '5', '1');
INSERT OR IGNORE INTO orderan_stiker VALUES ('2', 'RBBB-25110001', '1762489974838', '1', '1');
INSERT OR IGNORE INTO orderan_stiker VALUES ('3', 'RBBB-25110001', '1762490076326', '1', '1');
INSERT OR IGNORE INTO orderan_stiker VALUES ('4', 'RBBB-25110001', '1762490572839', '1', '1');

INSERT OR IGNORE INTO orderan_stiker_rinci VALUES ('3', '5', '1', '1');
INSERT OR IGNORE INTO orderan_stiker_rinci VALUES ('4', '1', '2', '1');
INSERT OR IGNORE INTO orderan_stiker_rinci VALUES ('5', '1', '3', '1');
INSERT OR IGNORE INTO orderan_stiker_rinci VALUES ('6', '1', '4', '1');


